# Generated by Django 6.0.4 on 2026-05-04 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('CONCLUIDA', 'Concluída')], default='ABERTA', max_length=20)),
            ],
        ),
    ]
