# Generated by Django 6.0.4 on 2026-05-04 23:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='data_entrega',
            field=models.DateField(default=datetime.date(2026, 5, 4)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarefa',
            name='prioridade',
            field=models.CharField(choices=[('URGENTE', 'Urgente'), ('NAO_URGENTE', 'Não Urgente')], default='NAO_URGENTE', max_length=20),
        ),
    ]
